# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Stepwise_Split <- function(x, y, n_models, max_variables_per_model, model_criterion, stop_criterion, stop_parameter, shrinkage, alpha, include_intercept, n_lambda, tolerance, max_iter, n_folds) {
    .Call('_stepSplitReg_Stepwise_Split', PACKAGE = 'stepSplitReg', x, y, n_models, max_variables_per_model, model_criterion, stop_criterion, stop_parameter, shrinkage, alpha, include_intercept, n_lambda, tolerance, max_iter, n_folds)
}

CV_Stepwise_Split <- function(x, y, n_models, max_variables_per_model, model_criterion, stop_criterion, stop_parameter, shrinkage, alpha, include_intercept, n_lambda, tolerance, max_iter, n_folds, n_threads) {
    .Call('_stepSplitReg_CV_Stepwise_Split', PACKAGE = 'stepSplitReg', x, y, n_models, max_variables_per_model, model_criterion, stop_criterion, stop_parameter, shrinkage, alpha, include_intercept, n_lambda, tolerance, max_iter, n_folds, n_threads)
}

